## Assignment_1: Part 4

In [ ]:
#Import the library
import numpy as np

In [19]:
#1. Array containing the numbers from 1 to 10

array = np.arange(1, 11)

# 2. Print the array
print (array)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# 3. Maximum and minimum values.
print("Max:", array.max())
print("Min:", array.min())


Max: 10
Min: 1


In [21]:
# 4. array of 5 zeros
five_zeros = np.zeros(5)
print("Zero:", five_zeros)

Zero: [0. 0. 0. 0. 0.]


In [22]:
# 5. array of 5 ones
five_ones = np.ones(5)
print("Ones:", five_ones)

Ones: [1. 1. 1. 1. 1.]


In [24]:
# 6. Matriz
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 7. display the matrix
print("Matriz:\n", matrix)

# 8. Shape
print("Shape:", matrix.shape)

Matriz:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
